name: orik

services:
  orik:
    build:
      context: ..
      dockerfile: Dockerfile
    image: orik:dev
    container_name: orik-dev
    restart: unless-stopped
    ports:
      - "13120:13120"
    volumes:
      - ../config:/app/config
