name: orik

services:
  orik:
    build:
      context: ..
      dockerfile: Dockerfile
    image: orik:latest
    container_name: orik
    restart: unless-stopped
    ports:
      - "13120:13120"
    volumes:
      - ../config:/app/config
